### ISSUE TITLE
Proposal for meta/run.yaml content being present in the composed image

### ISSUE THREAD

**Issue by miha-plesko** [mikelangelo-project/capstan#4]
Currently, Capstan runtime support makes use of `$CWD/meta/run.yaml` for composing and running an OSv image. Although this is fine for the composing, it gets tricky for running because `capstan run <IMAGE>` generally does not require user to be inside package root directory.

I propose the following solution:
### Composing image

File meta/run.yaml is present at package root directory (same as until now)

When user runs `capstan package compose` the content of meta/run.yaml file is processed and new files are generated inside the OSv image folder `/osv-runtime`:

Capstan should create a separate file for each named configuration e.g.

```
/osv-runtime
   |--burek
   |--pizza   <--------\
   |                    |
   |--default-runtime  /
```

Each runtime file should contain only one line representing the run command that is to be run inside OSv:

```
# content of file /osv-runtime/burek:
node burek.js
```

When user runs `capstan package compose` the boot command is set so that the agent is run. A capstan package must be implemented that provides agent funcionality. 
#### OSv Agent

Agent reads _cloud-init_ file. Based on cloud-init data it spawns a thread with appropriate run command.

TODO: Agent should be able to do more than just pick runtime! Since cloud-init script could contain some runtime-specific settings, say master-IP, and agent should be able to use them. At least it should be able to replace placeholders within run command. Must be careful, though, that agent needn't be adjusted when new runtime is added!
#### Default runtime

Symbolic link named `default-runtime` should be present in /osv-runtime folder. It should point to the runtime file that should be used if no runconfig is present in cloud-init.
### Running image

With changes above, Capstan shouldn't be required to run image. OpenStack could run it with arbitrary hypervisor as long as it provides cloud-init.

The `capstan run` command could therefore be changed. Parameter --runconfig would result in init-file be created and passed to the OSv while run command of the composed image should remain untouched (i.e. Agent will be run).

**Comment by miha-plesko** [comment]
@gberginc Could you comment on this? I'm really looking forward to hear your opinion.

**Comment by gberginc** [comment]
Generally speaking, the proposal looks like what we've discussed already. However, it lacks some of the details that I'd like to see added before we actually implement this functionality.

* One thing that is missing to me (probably just lack of a reference) is how the users provide the configurations. Are they still part of meta/run.yaml? And Capstan will be converting them to `/osv-runtime`?
* will this patch completely remove the "run" command of Capstan? As you write in the proposal, `capstan package compose` sets the main runtime to the agent, however if I change that I will no longer be able to launch predefined apps through the agent.
* does Agent provide any kind of API through OSv's REST?
* the example says `node burek.js`: does this require Agent to know about how to run the Node.JS server or is this something Capstan will work out? For example, the command will actually be `/node burek.js` (since we have a symlink `/node` to `/bin/libnode-4.4.5.so` in the Node.JS package?
* how are you going to support the cloud-init when running locally (without OpenStack or Amazon)? Will it build the second disk image and pass it to the instance using https://github.com/cloudius-systems/osv/commit/56c6195b252b127c7fe90cb9fa46c370b384b51a?
* regarding additional functionalities of the Agent: we have to be very careful with that as this might then just become a really complex and specific (meaning that we'd have to customise it too-often)
* for the sake of running apps, I wonder if it would be sufficient to extend OSv's cloud-init support with additional module that would simply accept a command to launch
* if we need a specific agent we might simply consider extending (augmenting) the REST API to support additional features. My guess is that this would also allow us to use such a logic for Murano agents in case we go with that.

**Comment by gberginc** [comment]
Spec proposal moved to a separate PR #6. Once finished, it will be propagated into one or more issues.
